### PR TITLE
Fixes and Customization for CircuitPython

### PR DESCRIPTION
**Pull request by microdev1**

### CODE REVIEW

**Review by dhalbert — COMMENTED** [review]
Looks innocuous, but are these to fix compilation issues? Should they be PR'd upstream?

**Comment by microdev1** [comment]
The following is customization for CP. Other changes are to fix compilation issues.
```c
bool i2s_lcd_acquire_nonblocking(i2s_lcd_handle_t handle, TickType_t ticks_to_wait) {
    i2s_lcd_driver_t *i2s_lcd_drv = (i2s_lcd_driver_t *)handle;
    return xSemaphoreTake(i2s_lcd_drv->mutex, ticks_to_wait);
}
```

**Review by dhalbert — APPROVED** [review]
These look fine. I think it would be good to PR upstream, including the added nonblocking routine.

**Comment by microdev1** [comment]
I updated the function so it better fits in with other espressif functions now. Also, made upstream PR https://github.com/espressif/esp-iot-solution/pull/216.

**Comment by microdev1** [comment]
@dhalbert This can be merged now

**Pull request closed without merging**
